name: Release WASM (GitHub Pages)
on:
  push:
    tags: ["v*"]

env:
  PUBLIC_URL: /simuverse/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build | Trunk
        run: |
          cd launchers/wasm-gh-pages
          trunk build --release --public-url ${{ env.PUBLIC_URL }}

      - name: Post Build | Upload dist
        uses: actions/upload-artifact@v3
        with:
          path: ./launchers/wasm-gh/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Download dist
        uses: actions/download-artifact@v3

      - name: Setup | Place dist
        run: mv ./artifact ./dist

      - name: Deploy | Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/